version: "3.0"
services:
  limesurvey:
    build:
      context: 4.0/apache/
      dockerfile: Dockerfile
    volumes:
      - ./data/surveys:/var/www/html/upload/surveys
      - ./data/config.php:/var/www/html/application/config/config.php
    links:
      - lime-db
    depends_on:
      - lime-db
    networks:
      - proxy
      - default
    environment:
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=MySQL-userpwd"
      - "ADMIN_PASSWORD=foobar"         # HIER PASSWORT ANPASSEN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.limesurvey.entrypoints=http"
      - "traefik.http.routers.limesurvey.rule=Host(`umfrage.example.com`)"          # HIER DOMAIN EINGEBEN
      - "traefik.http.middlewares.limesurvey-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.limesurvey.middlewares=limesurvey-https-redirect"
      - "traefik.http.routers.limesurvey-secure.entrypoints=https"
      - "traefik.http.routers.limesurvey-secure.rule=Host(`umfrage.example.com`)"   # HIER DOMAIN EINGEBEN
      - "traefik.http.routers.limesurvey-secure.tls=true"
      - "traefik.http.routers.limesurvey-secure.tls.certresolver=http"
      - "traefik.http.routers.limesurvey-secure.service=limesurvey"
      - "traefik.http.services.limesurvey.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.limesurvey-secure.middlewares=secHeaders@file"
  lime-db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_PASSWORD=MySQL-userpwd"
      - "MYSQL_ROOT_PASSWORD=MySQL-rootpwd"

networks:
  proxy:
    external: true

